pipeline {
    agent any

    parameters {
        string(
            name: 'SITE_URL',
            defaultValue: 'https://wasm.insightlearn.cloud',
            description: 'Target URL for load testing'
        )
        choice(
            name: 'LOAD_LEVEL',
            choices: ['heavy', 'medium', 'light', 'stress'],
            description: 'Load testing intensity level'
        )
        string(
            name: 'EMAIL_RECIPIENTS',
            defaultValue: 'marcello.pasqui@gmail.com',
            description: 'Email addresses for test results'
        )
    }

    triggers {
        // Run every Sunday at 2:00 AM
        cron('0 2 * * 0')
    }

    environment {
        SITE_URL = "${params.SITE_URL}"
        LOAD_LEVEL = "${params.LOAD_LEVEL}"
        TIMESTAMP = sh(script: 'date +%Y%m%d_%H%M%S', returnStdout: true).trim()
    }

    stages {
        stage('Preparation') {
            steps {
                echo "========================================="
                echo "Weekly Heavy Load Testing - Build #${env.BUILD_NUMBER}"
                echo "========================================="
                echo "Site URL: ${env.SITE_URL}"
                echo "Load Level: ${env.LOAD_LEVEL}"
                echo "Start Time: ${env.TIMESTAMP}"
                echo "========================================="

                // Verify scripts are executable
                sh 'chmod +x jenkins/scripts/*.sh'
            }
        }

        stage('Pre-Test Health Check') {
            steps {
                script {
                    echo "Checking site availability..."
                    def mainSiteStatus = sh(
                        script: "curl -s -o /dev/null -w '%{http_code}' ${env.SITE_URL}",
                        returnStdout: true
                    ).trim()

                    if (mainSiteStatus != '200') {
                        error("Site is not accessible: HTTP ${mainSiteStatus}")
                    }

                    echo "✅ Main site: ${mainSiteStatus}"
                }
            }
        }

        stage('Heavy Load Testing') {
            steps {
                script {
                    echo "========================================="
                    echo "Running ${env.LOAD_LEVEL} load test..."
                    echo "========================================="

                    // Run load test with specified level
                    sh """
                        ./jenkins/scripts/load-test.sh ${env.LOAD_LEVEL}
                    """
                }
            }
        }

        stage('Performance Analysis') {
            steps {
                script {
                    echo "Analyzing performance metrics..."

                    // Check if report was generated
                    sh """
                        if [ -f load-test-report-*.txt ]; then
                            echo "✅ Load test report generated"
                            cat load-test-report-*.txt
                        else
                            echo "⚠️  No load test report found"
                        fi
                    """
                }
            }
        }

        stage('Post-Test Health Check') {
            steps {
                script {
                    echo "Verifying site is still healthy after load test..."

                    def postTestStatus = sh(
                        script: "curl -s -o /dev/null -w '%{http_code}' ${env.SITE_URL}",
                        returnStdout: true
                    ).trim()

                    if (postTestStatus != '200') {
                        error("Site unhealthy after load test: HTTP ${postTestStatus}")
                    }

                    echo "✅ Post-test health check: ${postTestStatus}"
                }
            }
        }

        stage('Generate Summary Report') {
            steps {
                script {
                    def reportFile = "weekly-load-test-${env.TIMESTAMP}.md"

                    sh """
                        cat > ${reportFile} << 'EOF'
# Weekly Heavy Load Test Report

**Date**: \$(date '+%Y-%m-%d %H:%M:%S')
**Build**: #${env.BUILD_NUMBER}
**Site**: ${env.SITE_URL}
**Load Level**: ${env.LOAD_LEVEL}

## Test Configuration

\$(cat jenkins/scripts/load-test.sh | grep -A 20 "case \\\$LOAD_TYPE")

## Test Results

\$(cat load-test-report-*.txt 2>/dev/null || echo "No detailed results available")

## Status

- Pre-test Health: ✅ PASSED
- Load Test Execution: ✅ COMPLETED
- Post-test Health: ✅ PASSED

## Next Steps

- Review response times for degradation trends
- Check Grafana dashboards for detailed metrics
- Investigate any failures or warnings

---
**Generated by Jenkins Build #${env.BUILD_NUMBER}**
EOF
                        cat ${reportFile}
                    """

                    // Archive the report
                    archiveArtifacts artifacts: "weekly-load-test-*.md,load-test-report-*.txt", allowEmptyArchive: true
                }
            }
        }
    }

    post {
        success {
            emailext(
                subject: "✅ Weekly Load Test PASSED - Build #${env.BUILD_NUMBER}",
                body: """
Weekly heavy load testing completed successfully!

Build: #${env.BUILD_NUMBER}
Site: ${env.SITE_URL}
Load Level: ${env.LOAD_LEVEL}
Timestamp: ${env.TIMESTAMP}

All stages passed. Check Jenkins for detailed results:
${env.BUILD_URL}

View archived reports:
${env.BUILD_URL}artifact/

---
InsightLearn Automated Testing System
                """,
                to: "${params.EMAIL_RECIPIENTS}",
                attachLog: true
            )
        }

        failure {
            emailext(
                subject: "❌ Weekly Load Test FAILED - Build #${env.BUILD_NUMBER}",
                body: """
Weekly heavy load testing FAILED!

Build: #${env.BUILD_NUMBER}
Site: ${env.SITE_URL}
Load Level: ${env.LOAD_LEVEL}
Timestamp: ${env.TIMESTAMP}

Check Jenkins console output for details:
${env.BUILD_URL}console

Immediate action required!

---
InsightLearn Automated Testing System
                """,
                to: "${params.EMAIL_RECIPIENTS}",
                attachLog: true
            )
        }

        unstable {
            emailext(
                subject: "⚠️ Weekly Load Test UNSTABLE - Build #${env.BUILD_NUMBER}",
                body: """
Weekly heavy load testing completed with warnings!

Build: #${env.BUILD_NUMBER}
Site: ${env.SITE_URL}
Load Level: ${env.LOAD_LEVEL}
Timestamp: ${env.TIMESTAMP}

Some tests passed but performance may be degraded.
Check Jenkins for details:
${env.BUILD_URL}

---
InsightLearn Automated Testing System
                """,
                to: "${params.EMAIL_RECIPIENTS}",
                attachLog: true
            )
        }

        always {
            echo "========================================="
            echo "Weekly Load Test Completed"
            echo "Build: #${env.BUILD_NUMBER}"
            echo "Status: ${currentBuild.result}"
            echo "========================================="
        }
    }
}
