#!/bin/bash
# Create REAL MP4 Test Videos for InsightLearn
# Uses FFmpeg to generate actual playable video content

set -e

API_URL="http://localhost:31081"
VIDEO_DIR="/tmp/real-test-videos"
ADMIN_EMAIL="admin@insightlearn.cloud"
ADMIN_PASSWORD="Admin123!Secure"

# Configuration
TOTAL_VIDEOS=10      # 10 test videos
DURATION_SECS=30     # 30 seconds each
RESOLUTION="1280x720" # 720p

echo "🎬 Creating REAL MP4 Test Videos for InsightLearn"
echo "=================================================="
echo ""
echo "Configuration:"
echo "  - Videos: $TOTAL_VIDEOS × ${DURATION_SECS}s (720p)"
echo "  - Output: $VIDEO_DIR"
echo ""

# Check FFmpeg
if ! command -v ffmpeg &> /dev/null; then
    echo "❌ FFmpeg not installed. Install with: sudo dnf install ffmpeg"
    exit 1
fi

# ============================================
# 1. Authentication
# ============================================
echo "🔐 Authenticating..."
LOGIN_RESPONSE=$(curl -s -X POST "$API_URL/api/auth/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\"}")

TOKEN=$(echo "$LOGIN_RESPONSE" | jq -r '.Token // .token // empty')
USER_ID=$(echo "$LOGIN_RESPONSE" | jq -r '.User.Id // .userId // empty')

if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
    echo "❌ Auth failed: $LOGIN_RESPONSE"
    exit 1
fi

echo "✅ Authenticated (UserID: $USER_ID)"
echo ""

# ============================================
# 2. Generate Real MP4 Video Files with FFmpeg
# ============================================
echo "📦 Generating $TOTAL_VIDEOS real MP4 video files..."
mkdir -p "$VIDEO_DIR"

COLORS=("blue" "red" "green" "yellow" "purple" "orange" "pink" "cyan" "lime" "magenta")

for i in $(seq 1 $TOTAL_VIDEOS); do
    FILE="$VIDEO_DIR/test-video-$(printf '%03d' $i).mp4"
    COLOR=${COLORS[$((i-1))]}

    if [ ! -f "$FILE" ]; then
        echo "  Generating video $i/$TOTAL_VIDEOS (${COLOR} background)..."

        # Create a real MP4 video with:
        # - Colored background
        # - Test pattern overlay
        # - Timer counter
        # - Audio tone
        ffmpeg -y -loglevel error \
            -f lavfi -i "color=c=${COLOR}:s=${RESOLUTION}:d=${DURATION_SECS}" \
            -f lavfi -i "sine=frequency=440:duration=${DURATION_SECS}" \
            -vf "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf:text='InsightLearn Test Video $i':fontsize=48:fontcolor=white:x=(w-text_w)/2:y=h/4,drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf:text='Time\: %{pts\:hms}':fontsize=36:fontcolor=white:x=(w-text_w)/2:y=h/2" \
            -c:v libx264 -preset ultrafast -crf 28 \
            -c:a aac -b:a 128k \
            -movflags +faststart \
            -t ${DURATION_SECS} \
            "$FILE" 2>/dev/null || {
                # Fallback: simpler video without fonts
                ffmpeg -y -loglevel error \
                    -f lavfi -i "testsrc2=s=${RESOLUTION}:d=${DURATION_SECS}" \
                    -f lavfi -i "sine=frequency=440:duration=${DURATION_SECS}" \
                    -c:v libx264 -preset ultrafast -crf 28 \
                    -c:a aac -b:a 128k \
                    -movflags +faststart \
                    -t ${DURATION_SECS} \
                    "$FILE"
            }

        # Verify it's a valid MP4
        if file "$FILE" | grep -q "MP4"; then
            SIZE=$(du -h "$FILE" | cut -f1)
            echo "    ✅ Created: $FILE ($SIZE)"
        else
            echo "    ❌ Failed to create valid MP4: $FILE"
        fi
    else
        echo "  Skipping video $i (already exists)"
    fi
done

echo ""
echo "✅ All video files generated"
echo ""

# ============================================
# 3. Get Category ID
# ============================================
echo "📂 Getting category..."
CATEGORIES=$(curl -s "$API_URL/api/categories" -H "Authorization: Bearer $TOKEN")
CATEGORY_ID=$(echo "$CATEGORIES" | jq -r '.[] | select(.Name | test("Stress|Test"; "i")) | .Id' | head -n1)

if [ -z "$CATEGORY_ID" ]; then
    CATEGORY_ID=$(echo "$CATEGORIES" | jq -r '.[0].Id')
fi

echo "✅ Using category: $CATEGORY_ID"
echo ""

# ============================================
# 4. Create Course and Upload Videos
# ============================================
echo "📚 Creating course with real videos..."

COURSE_JSON=$(cat <<EOF
{
    "title": "[TEST] Real Video Test Course",
    "description": "Test course with REAL playable MP4 videos generated by FFmpeg. Each video is 30 seconds with a colored background, timer, and audio tone.",
    "shortDescription": "Real playable test videos",
    "categoryId": "$CATEGORY_ID",
    "instructorId": "$USER_ID",
    "price": 0.00,
    "level": "Beginner",
    "language": "en",
    "estimatedDurationMinutes": 5,
    "requirements": "None",
    "whatYouWillLearn": "Video streaming testing",
    "hasCertificate": false
}
EOF
)

COURSE_RESPONSE=$(curl -s -X POST "$API_URL/api/courses" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d "$COURSE_JSON")

COURSE_ID=$(echo "$COURSE_RESPONSE" | jq -r '.Id // .id // empty')

if [ -z "$COURSE_ID" ] || [ "$COURSE_ID" = "null" ]; then
    echo "❌ Failed to create course: $COURSE_RESPONSE"
    exit 1
fi

echo "✅ Course created: $COURSE_ID"

# Create section
SECTION_JSON='{"title":"Test Videos","description":"Real MP4 test videos","orderIndex":1}'
SECTION_RESPONSE=$(curl -s -X POST "$API_URL/api/courses/$COURSE_ID/sections" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d "$SECTION_JSON")

SECTION_ID=$(echo "$SECTION_RESPONSE" | jq -r '.Id // .id // empty')

echo "✅ Section created: $SECTION_ID"
echo ""

# Upload videos and create lessons
echo "📤 Uploading videos..."
UPLOADED=0

for i in $(seq 1 $TOTAL_VIDEOS); do
    VIDEO_FILE="$VIDEO_DIR/test-video-$(printf '%03d' $i).mp4"

    if [ -f "$VIDEO_FILE" ]; then
        # Create lesson
        LESSON_JSON='{"title":"Lesson '$i' - Video","description":"Test video lesson","type":"Video","orderIndex":'$i',"durationMinutes":1,"isFree":true}'

        LESSON_RESPONSE=$(curl -s -X POST "$API_URL/api/courses/$COURSE_ID/sections/$SECTION_ID/lessons" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d "$LESSON_JSON")

        LESSON_ID=$(echo "$LESSON_RESPONSE" | jq -r '.Id // .id // empty')

        if [ -z "$LESSON_ID" ] || [ "$LESSON_ID" = "null" ]; then
            LESSON_ID=$(uuidgen)
        fi

        # Upload video
        UPLOAD_RESPONSE=$(curl -s -w "\n%{http_code}" \
            -X POST "$API_URL/api/video/upload" \
            -H "Authorization: Bearer $TOKEN" \
            -F "file=@$VIDEO_FILE" \
            -F "lessonId=$LESSON_ID" \
            -F "userId=$USER_ID" \
            -F "title=Test Video $i" \
            --max-time 120)

        HTTP_CODE=$(echo "$UPLOAD_RESPONSE" | tail -n1)
        BODY=$(echo "$UPLOAD_RESPONSE" | sed '$d')

        if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "201" ]; then
            VIDEO_ID=$(echo "$BODY" | jq -r '.FileId // .fileId // empty')
            UPLOADED=$((UPLOADED + 1))
            echo "  ✅ Video $i uploaded (ID: $VIDEO_ID)"

            # Update lesson with video URL
            UPDATE_LESSON='{"videoUrl":"/api/video/stream/'$VIDEO_ID'"}'
            curl -s -X PUT "$API_URL/api/courses/$COURSE_ID/sections/$SECTION_ID/lessons/$LESSON_ID" \
                -H "Authorization: Bearer $TOKEN" \
                -H "Content-Type: application/json" \
                -d "$UPDATE_LESSON" > /dev/null
        else
            echo "  ❌ Video $i failed (HTTP $HTTP_CODE)"
        fi
    fi
done

echo ""
echo ""

# ============================================
# 5. Report
# ============================================
echo "📈 FINAL REPORT"
echo "==============="
echo ""
echo "📤 Uploads:"
echo "  ✅ Successful: $UPLOADED / $TOTAL_VIDEOS"
echo ""
echo "🌐 Test URL:"
echo "  https://www.insightlearn.cloud/courses/$COURSE_ID"
echo ""

# Get first lesson ID for direct link
FIRST_LESSON=$(curl -s "$API_URL/api/courses/$COURSE_ID" -H "Authorization: Bearer $TOKEN" | jq -r '.Sections[0].Lessons[0].Id // empty')
if [ -n "$FIRST_LESSON" ]; then
    echo "🎬 Direct video lesson link:"
    echo "  https://www.insightlearn.cloud/learn/$COURSE_ID/$FIRST_LESSON"
fi

echo ""
echo "🧹 Keeping temp files at: $VIDEO_DIR"
echo "   (delete manually when done testing: rm -rf $VIDEO_DIR)"
echo ""
echo "🎉 DONE!"
