using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace InsightLearn.Core.Entities;

/// <summary>
/// Subtitle track entity for video lessons - supports all world languages
/// </summary>
public class SubtitleTrack
{
    /// <summary>
    /// Unique identifier for the subtitle track
    /// </summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Foreign key to the Lesson this subtitle belongs to
    /// </summary>
    [Required]
    public Guid LessonId { get; set; }

    /// <summary>
    /// ISO 639-1 language code (e.g., "en", "it", "es", "fr", "de", "pt", "ru", "zh", "ja", "ko", "ar", "hi")
    /// </summary>
    [Required]
    [StringLength(10)]
    public string Language { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable label for the language (e.g., "English", "Italiano", "Español", "Français", "Deutsch", "Português", "Русский", "中文", "日本語", "한국어", "العربية", "हिन्दी")
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Label { get; set; } = string.Empty;

    /// <summary>
    /// URL or path to the WebVTT subtitle file
    /// </summary>
    [Required]
    [StringLength(500)]
    public string FileUrl { get; set; } = string.Empty;

    /// <summary>
    /// Track kind: "subtitles", "captions", or "descriptions"
    /// subtitles = translation of dialogue
    /// captions = transcription + sound effects (for accessibility)
    /// descriptions = audio descriptions for visually impaired
    /// </summary>
    [StringLength(20)]
    public string Kind { get; set; } = "subtitles";

    /// <summary>
    /// Whether this subtitle track should be enabled by default
    /// Only one track per lesson should have this set to true
    /// </summary>
    public bool IsDefault { get; set; }

    /// <summary>
    /// Whether this subtitle track is active and should be displayed
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// Size of the WebVTT file in bytes
    /// </summary>
    public long? FileSize { get; set; }

    /// <summary>
    /// Total number of cue entries in the subtitle file
    /// </summary>
    public int? CueCount { get; set; }

    /// <summary>
    /// Duration covered by subtitles in seconds
    /// </summary>
    public int? DurationSeconds { get; set; }

    /// <summary>
    /// When this subtitle track was created
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When this subtitle track was last updated
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// User who created/uploaded this subtitle
    /// </summary>
    public Guid? CreatedByUserId { get; set; }

    /// <summary>
    /// Whether this subtitle was auto-generated by Whisper ASR
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// Source of auto-generation (e.g., "whisper-asr", "manual")
    /// </summary>
    [StringLength(50)]
    public string? GenerationSource { get; set; }

    /// <summary>
    /// Navigation property to the Lesson
    /// </summary>
    [JsonIgnore]
    public virtual Lesson Lesson { get; set; } = null!;

    /// <summary>
    /// Navigation property to the User who created this subtitle
    /// </summary>
    [JsonIgnore]
    public virtual User? CreatedBy { get; set; }
}
